### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [FedorovaDarya/2048#1]
1. Не стоит использовать "магические числа", лучше заменить их именованными константами.
1. Лучше сделать конструктор `Cell`, который принимает содержимое, у Вас ведь не бывает ситуаций, когда в клетке должен быть `null`.
1. Лучше не привязываться к кодам клавиш (`KeyEvent`), а сделать свой `enum`.
1. Методы `Up`, `Down`, `Left` и `Right`, кроме того, что должны называться с маленькой буквы, подозрительно похожи друг на друга. Попробуйте как-то избавиться от этого дублирования кода.
1. Вы уверены, что условие `isFail` верное?

**Comment by DariyaFedorova** [comment]
1.Исправлено
2.Сделано
3.Сделано
4. Эти функции пришлось полностью переписать(в них были алгоритмические ошибки). В итоге они стали немного компактнее и выделяться "повторяющийся код" стал в меньшем объеме, 4 строки. При попытке переписать всё в одну функцию место в коде всё занимало примерно столько же, при этом я ещё и запуталась. Читать этот код будет очень нериятно. Считаю, что лучше оставить эти функции как есть.
5.Исправлено(двигаем поле во все стороны. если все клетки остались на своих местах, значит действительно проигрыш)
